[project]
name = "tools-go-gerencial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymongo>=4.15.5",
    "streamlit>=1.53.0",
    "supabase>=2.27.0",
]
